CREATE USER 'portal_user'@'localhost' IDENTIFIED BY 'portal_pass';

GRANT SELECT, INSERT, UPDATE, REFERENCES, DELETE, CREATE, DROP, ALTER, INDEX, TRIGGER, CREATE VIEW, SHOW VIEW, ALTER ROUTINE, CREATE ROUTINE, CREATE TEMPORARY TABLES, LOCK TABLES, EVENT ON `portaldb`.* TO 'portal_user'@'localhost';

GRANT GRANT OPTION ON `notedb`.* TO 'portal_user'@'localhost';
